import type { NextPage } from "next";
import Head from "next/head";
import styled from "@emotion/styled";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Article>
        <Iframe
          src="https://www.youtube.com/embed/XQPNWMJec1I"
          title="YouTube video player"
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        ></Iframe>
      </Article>
    </div>
  );
};

const Article = styled.article`
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`;
const Iframe = styled.iframe`
  width: 50vw;
  height: 50vh;
`;

export default Home;
